package gopwa

import "github.com/stretchr/testify/mock"

// MockSignatory is an autogenerated mock type for the Signatory type
type MockSignatory struct {
	mock.Mock
}

// Method provides a mock function with given fields:
func (_m *MockSignatory) Method() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Sign provides a mock function with given fields: _a0
func (_m *MockSignatory) Sign(_a0 string) []byte {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// Version provides a mock function with given fields:
func (_m *MockSignatory) Version() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
