package gopwa

import (
	"net/url"

	"github.com/stretchr/testify/mock"
)

// MockRequest is an autogenerated mock type for the Request type
type MockRequest struct {
	mock.Mock
}

// Action provides a mock function with given fields:
func (_m *MockRequest) Action() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AddValues provides a mock function with given fields: _a0
func (_m *MockRequest) AddValues(_a0 url.Values) url.Values {
	ret := _m.Called(_a0)

	var r0 url.Values
	if rf, ok := ret.Get(0).(func(url.Values) url.Values); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(url.Values)
		}
	}

	return r0
}
